SELECT 
USUARIO.Nome_Usuário,
USUARIO.Cpf,
SISTEMA.Nome_Sistema,
ORGAOS.Nome_Orgao,
CARGO.Nome_Cargo


FROM USUARIO
JOIN
CARGO
ON
USUARIO.Id_Cargo = CARGO.Id_Cargo
JOIN
ORGAOS
ON
USUARIO.Id_Orgao = ORGAOS.Id_Orgao
JOIN
SISTEMA
ON
ORGAOS.Id_Sistema = SISTEMA.Id_Sistema


SELECT USUARIO.Cpf, LEFT(USUARIO.Cpf, 3) AS CPF_MASCARADO FROM USUARIO;